apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movie-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/CCAssignment-25/tickbazaar-cd.git'
    path: 'charts/movie'
    targetRevision: main
    helm:
      valueFiles:
      - values.yaml
      values: |
        image:
          tag: v1
        hpa:
          enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
