replicaCount: 1

image:
  repository: asia-south1-docker.pkg.dev/focused-zephyr-478716-n0/cc-assignment/booking-svc
  tag: "v1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4004

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20

istio:
  enabled: true
  prefix: /booking
  gateway: istio-system/public-gateway


env: 
  "PORT": "4004"
  "SEAT_SERVICE_URL": http://seat-app:4003
  "LOKI_URL": http://loki-gateway.loki.svc.cluster.local

secret_env:
  "BOOKING_DATABASE_URL": "postgresql://postgres:$a+GF*eux<y>0(-{@34.93.218.184:5432/ticketbazaar_bookings?schema=public"
  "INTERNAL_API_KEY": "yfbryggg4hg78y84hgj49gu4ugr3"
