apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bookings.fullname" . }}-secret
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret_env }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
