replicaCount: 1

image:
  repository: asia-south1-docker.pkg.dev/focused-zephyr-478716-n0/cc-assignment/theatre-svc
  tag: "v1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4002

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

istio:
  enabled: true
  prefix: /theatre
  gateway: istio-system/public-gateway


env: 
  "PORT": "4002"
  "LOKI_URL": http://loki-gateway.loki.svc.cluster.local

secret_env:
  "THEATRE_DATABASE_URL": "postgresql://postgres:$a+GF*eux<y>0(-{@34.93.218.184:5432/ticketbazaar_theatres?schema=public"
  "INTERNAL_API_KEY": "yfbryggg4hg78y84hgj49gu4ugr3"